# Config file for pipeline_count.py

## general options

# Copyright statement
copyright: cribbslab (2021)

cdna_fasta: Homo_sapiens.GRCh38.cdna.all.fa

genome_fasta: hg38.fa
 
junc_bed: hg38_geneset_all.bed

gtf: hg38_geneset_all.gtf

# Specify if the pipeline should run umi correction or not
correct: 1