################################################################
#
#
# Pipeline pipeline_bam2fastq.py configuration file for sphinxreport
#
# This pipeline.ini file lists some configuration options that you might 
# want a user to set automatically.
#
# Add pipeline specific options into separate sections
#
################################################################
## general options


# Project name
projectname: CGATProject

# Copyright statement
copyright: CGAT (2010-2014)

# The short X.Y version.
version: 0.1

# The full version, including alpha/beta/rc tags.
release: 0.1

data: data.dir

# hisat2 index options
hisat2_index: /t1-data/project/cribbslab/shared/resources/hisat2/hg38

# Featurecounts
gtf: geneset_all.gtf.gz


# Specify if the trimer correction method should be added
correct: 1

# Specify how many errors to remove
errors: 1

job_options: -t 48:00:00