name: tallytrin
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - cgatcore
  - pysam
  - biopython
  - scipy
  - pytest
  - numpy
  - pandas
  - python
  - tabix
  - regex
  - samtools
  - umi_tools
  - click
  - minimap2
  - flake8
  - cgat-apps
  - subread