################################################################
#
#
# Pipeline pipeline_10x.py configuration file for sphinxreport
#
# This pipeline.yml file lists some configuration options that you might 
# want a user to set automatically.
#
# Add pipeline specific options into separate sections
#
################################################################
## general options


# Project name
projectname: CGATProject

# Copyright statement
copyright: CGAT (2010-2014)

# The short X.Y version.
version: 0.1

# The full version, including alpha/beta/rc tags.
release: 0.1

data: data.dir

# Specify number of cells to expect
cells: 2000

# STAR mapping options
star:
   options: -ax map-ont -p 0.9 --end-bonus 10 -N 3 

   fasta_genome: /t1-data/project/cribbslab/shared/resources/annotations/Human_mouse/hg38-mm10_HM.fa

   gene_options: ''

featurecounts:

   gtf: /t1-data/project/cribbslab/shared/resources/annotations/Human_mouse/hg38-mm10_HM_geneset_all.gtf
database:
   url: sqlite:///./csvdb

job_options: -t 48:00:00

# Specify the barcode length you would like for 10x,
# the default is 16 but for testing purposes this can be reduced
barcode: 16