################################################################
#
#
# Pipeline pipeline_10x.py configuration file for sphinxreport
#
# This pipeline.yml file lists some configuration options that you might 
# want a user to set automatically.
#
# Add pipeline specific options into separate sections
#
################################################################
## general options


# Project name
projectname: CGATProject

# Copyright statement
copyright: CGAT (2010-2014)

# The short X.Y version.
version: 0.1

# The full version, including alpha/beta/rc tags.
release: 0.1

data: data.dir

# Specify number of cells to expect
cells: 1500

# hisat2 mapping options
hisat2:
   options: '' 

   index_dir: /project/cribbslab/shared/resources/hisat2/

   index_name: hg38-mm10_HM

   threads: 5

   memory: 3.5G

umi_tools:

   pattern: CCCCCCCCCCCCCCCCNNNNNNNNNNNN

featurecounts:

   gtf: /project/cribbslab/shared/resources/annotations/Human_mouse/hg38-mm10_HM_geneset_all.gtf
   threads: 5
database:
   url: sqlite:///./csvdb

job_options: -t 48:00:00

# Specify the barcode length you would like for 10x,
# the default is 16 but for testing purposes this can be reduced
barcode: 16