################################################################
#
#
# Pipeline pipeline_nanopore.py configuration file for sphinxreport
#
# This pipeline.ini file lists some configuration options that you might 
# want a user to set automatically.
#
# Add pipeline specific options into separate sections
#
################################################################
## general options


# Project name
projectname: CGATProject

# Copyright statement
copyright: CGAT (2010-2014)

# The short X.Y version.
version: 0.1

# The full version, including alpha/beta/rc tags.
release: 0.1

data: data.dir

# is the bead made of a trimer?
trimer_beads: 0

# Number of reads to split the fastq file by for parallelization
# Needs to be a multiple of 4
split: 1000000


# To speed up the gene analysis you can strip sequence by specifying 1
strip-seq: 1

# minimap2 mapping options
minimap2:
   options: map-ont -p 0.9 --end-bonus 10 -N 3

   fasta_cdna: Homo_sapiens.GRCh38.cdna.all.fa

   fasta_genome: /ceph/project/cribbslab/shared/resources/index/hg38.fa

   junc_bed: --junc-bed /ceph/project/cribbslab/shared/resources/annotations/hg38_ensembl98/junc_bed/geneset_all.bed

   gene_options: ''

featurecounts:

   gtf: /ceph/project/cribbslab/shared/resources/annotations/hg38_ensembl98/junc_bed/geneset_all.bed

database:
   url: sqlite:///./csvdb

job_options: -t 48:00:00

# Expected number of cells in the experiment
cells: 1000

# Length of cell barcode 
barcode_len: 12
