################################################################
#
#
# Pipeline pipeline_10x.py configuration file for sphinxreport
#
# This pipeline.yml file lists some configuration options that you might 
# want a user to set automatically.
#
# Add pipeline specific options into separate sections
#
################################################################
## general options


# Project name
projectname: CGATProject

# Copyright statement
copyright: CGAT (2010-2014)

# The short X.Y version.
version: 0.1

# The full version, including alpha/beta/rc tags.
release: 0.1

data: data.dir


# Number of reads to split the fastq file by for parallelization
# Needs to be a multiple of 4
split: 1000000

# Specify number of cells to expect
cells: 2000

# To speed up the gene analysis you can strip sequence by specifying 1
strip-seq: 1

# minimap2 mapping options
minimap2:
   options: map-ont -p 0.9 --end-bonus 10 -N 3

   fasta_cdna: /t1-data/project/cribbslab/shared/resources/annotations/hg38-mm10.cdna.all.fa.gz

   fasta_genome: /t1-data/project/cribbslab/shared/resources/annotations/Human_mouse/hg38-mm10_HM.fa

   junc_bed: --junc-bed /t1-data/project/cribbslab/shared/resources/annotations/Human_mouse/hg38-mm10_coding_gene_sorted.bed

   gene_options: ''

featurecounts:

   gtf: /t1-data/project/cribbslab/shared/resources/annotations/Human_mouse/hg38-mm10_HM_geneset_all.gtf
   threads: 5
database:
   url: sqlite:///./csvdb


# run in CMI mode - this is where the PCR primer will be used as a UMI,
# this is so that the accuracy of the data can be measured: True 1, False 0
cmi_mode: 1

job_options: -t 48:00:00

# Specify the barcode length you would like for 10x,
# the default is 16 but for testing purposes this can be reduced
barcode: 16

# Specify the length of UMI
umi_length: 12

# Specify the amount of memory required for generating mtx format
mtx_memory: 200G

# specify min number of counts to make mtx files
mtx_mincounts: 3

mtx_filter: 3