################################################################
#
#
# Pipeline pipeline_nanopore.py configuration file for sphinxreport
#
# This pipeline.ini file lists some configuration options that you might 
# want a user to set automatically.
#
# Add pipeline specific options into separate sections
#
################################################################
## general options


# Project name
projectname: CGATProject

# Copyright statement
copyright: CGAT (2010-2014)

# The short X.Y version.
version: 0.1

# The full version, including alpha/beta/rc tags.
release: 0.1

# mapped bam file (sorted) data from output of mapped_genome.dir after running pipeline_
data: data.dir

# location of the intron bed file
intron_bed: intron.bed


# minimap2 mapping options
minimap2:
   options: -ax map-ont -p 0.9 --end-bonus 10 -N 3

   fasta_cdna: /media/caeruleus/cg1/resources/annotations/hg38_ensembl98/Homo_sapiens.GRCh38.cdna.all.fa

   fasta_genome: /media/caeruleus/cg1/resources/index/hg38.fa

   junc_bed: --junc-bed /media/caeruleus/cg1/resources/annotations/hg38_ensembl98/ensembl.dir/geneset_all.bed

   gene_options: ''

featurecounts:

   gtf: /media/caeruleus/cg1/resources/annotations/hg38_ensembl98/ensembl.dir/geneset_all.gtf.gz

database:
   url: sqlite:///./csvdb

job_options: -t 48:00:00

